In [21]:
import pandas as pd

df = pd.read_csv("telecom_customer_churn.csv")

In [26]:
df

Customer ID  Gender  Age Married  Number of Dependents          City  \
0     0002-ORFBO  Female   37     Yes                     0  Frazier Park   
1     0003-MKNFE    Male   46      No                     0      Glendale   
2     0004-TLHLJ    Male   50      No                     0    Costa Mesa   
3     0011-IGKFF    Male   78     Yes                     0      Martinez   
4     0013-EXCHZ  Female   75     Yes                     0     Camarillo   
...          ...     ...  ...     ...                   ...           ...   
7038  9987-LUTYD  Female   20      No                     0       La Mesa   
7039  9992-RRAMN    Male   40     Yes                     0     Riverbank   
7040  9992-UJOEL    Male   22      No                     0           Elk   
7041  9993-LHIEB    Male   21     Yes                     0  Solana Beach   
7042  9995-HOTOH    Male   36     Yes                     0   Sierra City   

      Zip Code  Latitude  Longitude  Number of Referrals  ...  \
0        93225     34.83    -119.00                    2  ...   
1        91206     34.16    -118.20                    0  ...   
2        92627     33.65    -117.92                    0  ...   
3        94553     38.01    -122.12                    1  ...   
4        93010     34.23    -119.08                    3  ...   
...        ...       ...        ...                  ...  ...   
7038     91941     32.76    -117.00                    0  ...   
7039     95367     37.73    -120.95                    1  ...   
7040     95432     39.11    -123.65                    0  ...   
7041     92075     33.00    -117.26                    5  ...   
7042     96125     39.60    -120.64                    1  ...   

       Payment Method Monthly Charge Total Charges  Total Refunds  \
0         Credit Card          65.60        593.30           0.00   
1         Credit Card          -4.00        542.40          38.33   
2     Bank Withdrawal          73.90        280.85           0.00   
3     Bank Withdrawal          98.00       1237.85           0.00   
4         Credit Card          83.90        267.40           0.00   
...               ...            ...           ...            ...   
7038      Credit Card          55.15        742.90           0.00   
7039  Bank Withdrawal          85.10       1873.70           0.00   
7040      Credit Card          50.30         92.75           0.00   
7041      Credit Card          67.85       4627.65           0.00   
7042  Bank Withdrawal          59.00       3707.60           0.00   

     Total Extra Data Charges Total Long Distance Charges Total Revenue  \
0                           0                      381.51        974.81   
1                          10                       96.21        610.28   
2                           0                      134.60        415.45   
3                           0                      361.66       1599.51   
4                           0                       22.14        289.54   
...                       ...                         ...           ...   
7038                        0                      606.84       1349.74   
7039                        0                      356.40       2230.10   
7040                        0                       37.24        129.99   
7041                        0                      142.04       4769.69   
7042                        0                        0.00       3707.60   

      Customer Status   Churn Category                   Churn Reason  
0              Stayed              NaN                            NaN  
1              Stayed              NaN                            NaN  
2             Churned       Competitor  Competitor had better devices  
3             Churned  Dissatisfaction        Product dissatisfaction  
4             Churned  Dissatisfaction            Network reliability  
...               ...              ...                            ...  
7038           Stayed              NaN                           

In [23]:
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Married', 'Number of Dependents',
       'City', 'Zip Code', 'Latitude', 'Longitude', 'Number of Referrals',
       'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Customer Status', 'Churn Category', 'Churn Reason'],
      dtype='object')

In [24]:
num_cols = ['Customer ID', 'Gender', 'Age', 'Married', 'Number of Dependents',
       'City', 'Zip Code', 'Latitude', 'Longitude', 'Number of Referrals',
       'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Customer Status', 'Churn Category', 'Churn Reason']

In [4]:
import numpy as np
# replace blank spaces with NaN
df['Total Charges'] = df['Total Charges'].replace(' ', np.nan)

# convert to float and replace NaN values with median
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df['Total Charges'] = df['Total Charges'].fillna(df['Total Charges'].median())

# check for outliers again
Q1 = df['Total Charges'].quantile(0.25)
Q3 = df['Total Charges'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR
lower_bound = Q1 - 1.5 * IQR
outliers = df[(df['Total Charges'] < lower_bound) | (df['Total Charges'] > upper_bound)]
print(outliers)


Empty DataFrame
Columns: [CustomerID, Count, Country, State, City, Zip Code, Lat Long, Latitude, Longitude, Gender, Senior Citizen, Partner, Dependents, Tenure Months, Phone Service, Multiple Lines, Internet Service, Online Security, Online Backup, Device Protection, Tech Support, Streaming TV, Streaming Movies, Contract, Paperless Billing, Payment Method, Monthly Charges, Total Charges, Churn Label, Churn Value, Churn Score, CLTV, Churn Reason]
Index: []

[0 rows x 33 columns]


In [5]:
# replace NaN values with median
df['Total Charges'] = df['Total Charges'].fillna(df['Total Charges'].median())

# check for outliers again
Q1 = df['Total Charges'].quantile(0.25)
Q3 = df['Total Charges'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['Total Charges'] < lower_bound) | (df['Total Charges'] > upper_bound)]


In [28]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df['Monthly Charge'] = pd.to_numeric(df['Monthly Charge'], errors='coerce')

df['Ratio'] = df['Total Charges'] / df['Monthly Charge']


In [29]:
# check for null values
null_cols = df.columns[df.isnull().any()]
print("Columns with null values:", null_cols)

# count number of null values in each column
null_counts = df[null_cols].isnull().sum()
print("\nNumber of null values in each column:\n", null_counts)


Columns with null values: Index(['Avg Monthly Long Distance Charges', 'Multiple Lines', 'Internet Type',
       'Avg Monthly GB Download', 'Online Security', 'Online Backup',
       'Device Protection Plan', 'Premium Tech Support', 'Streaming TV',
       'Streaming Movies', 'Streaming Music', 'Unlimited Data',
       'Churn Category', 'Churn Reason'],
      dtype='object')

Number of null values in each column:
 Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Churn Category                       5174
Churn Reason                         5

In [30]:
# fill missing values for numerical columns with median
num_cols = ['Avg Monthly Long Distance Charges', 'Avg Monthly GB Download', 'Total Charges']
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# fill missing values for categorical columns with mode
cat_cols = ['Multiple Lines', 'Internet Type', 'Online Security', 'Online Backup', 'Device Protection Plan', 'Premium Tech Support', 'Streaming TV', 'Streaming Movies', 'Streaming Music', 'Unlimited Data']
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

# fill missing values for Churn Category and Churn Reason with "Not Applicable"
df[['Churn Category', 'Churn Reason']] = df[['Churn Category', 'Churn Reason']].fillna("Not Applicable")


In [32]:
df

Customer ID  Gender  Age Married  Number of Dependents          City  \
0     0002-ORFBO  Female   37     Yes                     0  Frazier Park   
1     0003-MKNFE    Male   46      No                     0      Glendale   
2     0004-TLHLJ    Male   50      No                     0    Costa Mesa   
3     0011-IGKFF    Male   78     Yes                     0      Martinez   
4     0013-EXCHZ  Female   75     Yes                     0     Camarillo   
...          ...     ...  ...     ...                   ...           ...   
7038  9987-LUTYD  Female   20      No                     0       La Mesa   
7039  9992-RRAMN    Male   40     Yes                     0     Riverbank   
7040  9992-UJOEL    Male   22      No                     0           Elk   
7041  9993-LHIEB    Male   21     Yes                     0  Solana Beach   
7042  9995-HOTOH    Male   36     Yes                     0   Sierra City   

      Zip Code  Latitude  Longitude  Number of Referrals  ...  Monthly Charge  \
0        93225     34.83    -119.00                    2  ...           65.60   
1        91206     34.16    -118.20                    0  ...           -4.00   
2        92627     33.65    -117.92                    0  ...           73.90   
3        94553     38.01    -122.12                    1  ...           98.00   
4        93010     34.23    -119.08                    3  ...           83.90   
...        ...       ...        ...                  ...  ...             ...   
7038     91941     32.76    -117.00                    0  ...           55.15   
7039     95367     37.73    -120.95                    1  ...           85.10   
7040     95432     39.11    -123.65                    0  ...           50.30   
7041     92075     33.00    -117.26                    5  ...           67.85   
7042     96125     39.60    -120.64                    1  ...           59.00   

     Total Charges Total Refunds  Total Extra Data Charges  \
0           593.30          0.00                         0   
1           542.40         38.33                        10   
2           280.85          0.00                         0   
3          1237.85          0.00                         0   
4           267.40          0.00                         0   
...            ...           ...                       ...   
7038        742.90          0.00                         0   
7039       1873.70          0.00                         0   
7040         92.75          0.00                         0   
7041       4627.65          0.00                         0   
7042       3707.60          0.00                         0   

     Total Long Distance Charges Total Revenue Customer Status  \
0                         381.51        974.81          Stayed   
1                          96.21        610.28          Stayed   
2                         134.60        415.45         Churned   
3                         361.66       1599.51         Churned   
4                          22.14        289.54         Churned   
...                          ...           ...             ...   
7038                      606.84       1349.74          Stayed   
7039                      356.40       2230.10         Churned   
7040                       37.24        129.99          Joined   
7041                      142.04       4769.69          Stayed   
7042                        0.00       3707.60          Stayed   

       Churn Category                   Churn Reason   Ratio  
0      Not Applicable                 Not Applicable    9.04  
1      Not Applicable                 Not Applicable -135.60  
2          Competitor  Competitor had better devices    3.80  
3     Dissatisfaction        Product dissatisfaction   12.63  
4     Dissatisfaction            Network reliability    3.19  
...               ...                            ...     ...  
7038   Not Applicable                 Not Applicable   13.47  
7039  Dissatisfaction        Product dissatisfaction   22.02  
70

In [33]:
# create a list of categorical columns
cat_cols = ['Gender', 'Married', 'City', 'Phone Service', 'Multiple Lines',
            'Internet Service', 'Internet Type', 'Online Security', 'Online Backup',
            'Device Protection Plan', 'Premium Tech Support', 'Streaming TV',
            'Streaming Movies', 'Streaming Music', 'Unlimited Data',
            'Contract', 'Paperless Billing', 'Payment Method']

# create dummy variables for categorical columns
df = pd.get_dummies(df, columns=cat_cols)


In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

X = df.drop('Churn Category', axis=1)
y = df['Churn Category']

# Convert categorical variables to dummies
cat_cols = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=cat_cols, drop_first=True)

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate the logistic regression model
logreg = LogisticRegression()

# Fit the model to the training data
logreg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = logreg.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Create a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)


Accuracy: 0.7352732434350603
Confusion Matrix:
 [[   0    0    0   53    0    0]
 [   0    0    0  167    0    0]
 [   0    0    0   60    0    0]
 [   0    0    0 1036    0    0]
 [   0    0    0   42    0    0]
 [   0    0    0   51    0    0]]


In [39]:
# Importing lazypredict
from lazypredict.Supervised import LazyClassifier

# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Instantiating and fitting the LazyClassifier
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

# Printing the models and their accuracy scores
print(models)


100%|██████████| 29/29 [13:30<00:00, 27.96s/it] 

                               Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
BaggingClassifier                  1.00               1.00    None      1.00   
DecisionTreeClassifier             1.00               1.00    None      1.00   
LGBMClassifier                     0.99               0.96    None      0.99   
PassiveAggressiveClassifier        0.99               0.95    None      0.99   
RidgeClassifierCV                  0.99               0.95    None      0.99   
RidgeClassifier                    0.99               0.95    None      0.99   
LinearSVC                          0.99               0.95    None      0.99   
Perceptron                         0.97               0.91    None      0.97   
LogisticRegression                 0.97               0.88    None      0.97   
ExtraTreesClassifier               0.97               0.87    None      0.97   
NearestCentroid                    0.97 

In [40]:
models

Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
BaggingClassifier                  1.00               1.00    None      1.00   
DecisionTreeClassifier             1.00               1.00    None      1.00   
LGBMClassifier                     0.99               0.96    None      0.99   
PassiveAggressiveClassifier        0.99               0.95    None      0.99   
RidgeClassifierCV                  0.99               0.95    None      0.99   
RidgeClassifier                    0.99               0.95    None      0.99   
LinearSVC                          0.99               0.95    None      0.99   
Perceptron                         0.97               0.91    None      0.97   
LogisticRegression                 0.97               0.88    None      0.97   
ExtraTreesClassifier               0.97               0.87    None      0.97   
NearestCentroid                    0.97               0.87    None      0.97   
RandomForestClassifier             0.95               0.76    None      0.94   
AdaBoostClassifier                 0.88               0.50    None      0.85   
ExtraTreeClassifier                0.81               0.48    None      0.81   
GaussianNB                         0.83               0.48    None      0.82   
KNeighborsClassifier               0.83               0.39    None      0.79   
LinearDiscriminantAnalysis         0.78               0.33    None      0.75   
BernoulliNB                        0.85               0.33    None      0.80   
SVC                                0.84               0.32    None      0.79   
CalibratedClassifierCV             0.77               0.23    None      0.70   
LabelSpreading                     0.04               0.17    None      0.00   
LabelPropagation                   0.04               0.17    None      0.00   
DummyClassifier                    0.74               0.17    None      0.63   
SGDClassifier                      0.74               0.17    None      0.63   
QuadraticDiscriminantAnalysis      0.42               0.14    None      0.45   

                               Time Taken  
Model                                      
BaggingClassifier                    3.17  
DecisionTreeClassifier               1.40  
LGBMClassifier                       4.68  
PassiveAggressiveClassifier          8.31  
RidgeClassifierCV                  118.29  
RidgeClassifier                      4.65  
LinearSVC                            8.81  
Perceptron                           5.57  
LogisticRegression                   4.82  
ExtraTreesClassifier                 6.49  
NearestCentroid                      1.69  
RandomForestClassifier               6.08  
AdaBoostClassifier                  11.69  
ExtraTreeClassifier                  1.31  
GaussianNB                           2.16  
KNeighborsClassifier                 3.10  
LinearDiscriminantAnalysis          99.26  
BernoulliNB                          1.82  
SVC                                408.01  
CalibratedClassifierCV              24.22  
LabelSpreading                       4.30  
LabelPropagation                     4.20  
DummyClassifier                      1.18  
SGDClassifier                        8.19  
QuadraticDiscriminantAnalysis       62.36